# Generated by Django 5.0.6 on 2024-06-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderAnswer', models.IntegerField(verbose_name='')),
                ('signAnswer', models.IntegerField(verbose_name='')),
                ('cyclicAnswer', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='SetSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='StorePermutation',
            fields=[
                ('permutation', models.JSONField(primary_key=True, serialize=False, verbose_name='Two Line Dict')),
            ],
        ),
    ]
