#!/bin/bash

TOOLS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo TOOLS_ROOT

cd "$TOOLS_ROOT/../" && (flake8 --format=html --htmldir=flake-report --exclude system_test,src/antlr_generated,.venv,src/__pycache__ || true) && cd flake-report/ && python3 -m http.server
