services:
  motioninput:
    build: .
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - internal-services
networks:
   internal-services:
     name: internal-services
     driver: bridge
